source "https://rubygems.org"

gem "minima"

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-github-metadata"
end
